package io.imads

// Component Model bindings for imads-wasm.
// JS bindings are generated by jco from the WASM component.
// The engine interface is exported as module-level functions.
// The evaluator resource is implemented by the host (this code).

@JsModule("imads-wasm")
external object ImadsWasm {
    object engine {
        fun run(preset: String, env: dynamic, workers: Int): dynamic
        fun runWithEvaluator(preset: String, env: dynamic, workers: Int, evaluator: dynamic): dynamic
        fun runMulti(preset: String, env: dynamic, workers: Int, evaluator: dynamic): dynamic
    }
}

// ---- ImadsConfig (JS — stores preset name for Component Model) ----

actual class ImadsConfig private constructor(internal val presetName: String) : AutoCloseable {
    actual companion object {
        actual fun fromPreset(name: String): ImadsConfig {
            require(name in presetNames()) { "Unknown preset: $name" }
            return ImadsConfig(presetToWit(name))
        }

        actual fun presetNames(): List<String> =
            listOf("legacy_baseline", "balanced", "conservative", "throughput")
    }

    actual override fun close() {
        // No-op: Component Model manages resources automatically.
    }
}

// WIT preset enum uses kebab-case; map from underscore convention.
private fun presetToWit(name: String): String = name.replace('_', '-')

// Build a WIT env record as a JS object.
private fun buildWitEnv(env: ImadsEnv): dynamic {
    val obj = js("{}")
    obj["runId"] = env.runId.toDouble()
    obj["configHash"] = env.configHash.toDouble()
    obj["dataSnapshotId"] = env.dataSnapshotId.toDouble()
    obj["rngMasterSeed"] = env.rngMasterSeed.toDouble()
    return obj
}

// ---- ImadsEngine (JS via WASM Component Model) ----

actual class ImadsEngine actual constructor() : AutoCloseable {

    actual fun run(cfg: ImadsConfig, env: ImadsEnv, workers: Int): ImadsOutput {
        val witEnv = buildWitEnv(env)
        val out = ImadsWasm.engine.run(cfg.presetName, witEnv, workers)
        return extractOutput(out)
    }

    actual fun run(
        cfg: ImadsConfig,
        env: ImadsEnv,
        evaluator: ImadsEvaluator,
        numConstraints: Int,
        workers: Int,
    ): ImadsOutput {
        val witEnv = buildWitEnv(env)
        val witEval = createWitEvaluator(evaluator, numConstraints)
        val out = ImadsWasm.engine.runWithEvaluator(cfg.presetName, witEnv, workers, witEval)
        return extractOutput(out)
    }

    actual override fun close() {
        // No-op: Component Model manages resources automatically.
    }
}

// Create a JS evaluator resource object matching the WIT interface.
private fun createWitEvaluator(evaluator: ImadsEvaluator, numConstraints: Int): dynamic {
    val obj = js("{}")
    obj["mcSample"] = { x: dynamic, tau: Double, smc: Int, k: Int ->
        val xArr = DoubleArray(x.length as Int) { i -> x[i] as Double }
        val result = evaluator.mcSample(xArr, tau.toLong(), smc, k)
        result.toTypedArray()
    }
    obj["cheapConstraints"] = { x: dynamic ->
        val xArr = DoubleArray(x.length as Int) { i -> x[i] as Double }
        evaluator.cheapConstraints(xArr)
    }
    obj["numConstraints"] = { numConstraints }
    obj["searchDim"] = {
        evaluator.searchDim()
    }
    return obj
}

private fun extractOutput(out: dynamic): ImadsOutput {
    // Component Model output: { fBest: [f64] | undefined, xBest: [s64] | undefined, stats: {...} }
    val fBestArr = out.fBest
    val fBest: Double? = if (fBestArr == null || fBestArr == js("undefined")) {
        null
    } else {
        // option<list<f64>> → first element
        (fBestArr as Array<*>)[0] as Double
    }

    val xBestArr = out.xBest
    val xBest: LongArray = if (xBestArr == null || xBestArr == js("undefined")) {
        longArrayOf()
    } else {
        val arr = xBestArr as Array<*>
        LongArray(arr.size) { i -> (arr[i] as Number).toLong() }
    }

    val stats = out.stats
    return ImadsOutput(
        fBest = fBest,
        xBest = xBest,
        truthEvals = (stats.truthEvals as Number).toLong(),
        partialSteps = (stats.partialSteps as Number).toLong(),
        cheapRejects = (stats.cheapRejects as Number).toLong(),
        invalidEvalRejects = (stats.invalidEvalRejects as Number).toLong(),
    )
}
