package io.imads

import scala.scalajs.js
import scala.scalajs.js.annotation.*

// Component Model bindings for imads-wasm.
// JS bindings are generated by jco from the WASM component.

/** Facade for the jco-generated engine namespace. */
@js.native
@JSImport("imads-wasm", "engine")
object WasmEngine extends js.Object:
  def run(preset: String, env: js.Object, workers: Int): js.Dynamic = js.native
  def runWithEvaluator(preset: String, env: js.Object, workers: Int, evaluator: js.Object): js.Dynamic = js.native
  def runMulti(preset: String, env: js.Object, workers: Int, evaluator: js.Object): js.Dynamic = js.native

/** Scala.js platform backend via WASM Component Model. */
object ImadsPlatform extends ImadsPlatformOps:
  // With Component Model, config is just a preset name string.
  type ConfigHandle = String
  type EngineHandle = Unit

  def presetNames: Seq[String] =
    Seq("legacy_baseline", "balanced", "conservative", "throughput")

  def configFromPreset(name: String): String =
    require(presetNames.contains(name), s"Unknown preset: $name")
    name.replace('_', '-') // WIT preset enum uses kebab-case

  def configFree(handle: String): Unit = () // No-op
  def engineNew(): Unit = ()                 // No-op
  def engineFree(handle: Unit): Unit = ()    // No-op

  def engineRun(engine: Unit, cfg: String, env: Env, workers: Int): Output =
    val witEnv = buildWitEnv(env)
    extractOutput(WasmEngine.run(cfg, witEnv, workers))

  def engineRun(engine: Unit, cfg: String, env: Env,
                evaluator: Evaluator, numConstraints: Int, workers: Int): Output =
    val witEnv = buildWitEnv(env)
    val witEval = createWitEvaluator(evaluator, numConstraints)
    extractOutput(WasmEngine.runWithEvaluator(cfg, witEnv, workers, witEval))

  private def buildWitEnv(env: Env): js.Object =
    js.Dynamic.literal(
      runId = env.runId.toDouble,
      configHash = env.configHash.toDouble,
      dataSnapshotId = env.dataSnapshotId.toDouble,
      rngMasterSeed = env.rngMasterSeed.toDouble,
    )

  private def createWitEvaluator(evaluator: Evaluator, numConstraints: Int): js.Object =
    val mcSampleFn: js.Function4[js.Array[Double], Double, Int, Int, js.Array[Double]] =
      (x: js.Array[Double], tau: Double, smc: Int, k: Int) =>
        val xArr = x.toArray
        val result = evaluator.mcSample(xArr, tau.toLong, smc, k)
        js.Array(result*)

    val cheapConstraintsFn: js.Function1[js.Array[Double], Boolean] =
      (x: js.Array[Double]) =>
        evaluator.cheapConstraints(x.toArray)

    val numConstraintsFn: js.Function0[Int] = () => numConstraints

    val searchDimFn: js.Function0[js.UndefOr[Int]] = () =>
      evaluator.searchDim match
        case Some(d) => d
        case None    => js.undefined

    js.Dynamic.literal(
      mcSample = mcSampleFn,
      cheapConstraints = cheapConstraintsFn,
      numConstraints = numConstraintsFn,
      searchDim = searchDimFn,
    )

  private def extractOutput(out: js.Dynamic): Output =
    // Component Model: fBest is option<list<f64>> → Array[Double] | undefined
    val fBestArr = out.fBest.asInstanceOf[Any]
    val fBest = fBestArr match
      case arr: js.Array[?] if arr.nonEmpty => Some(arr(0).asInstanceOf[Double])
      case _                               => None

    val xBestArr = out.xBest.asInstanceOf[Any]
    val xBest = xBestArr match
      case arr: js.Array[?] => arr.map(_.asInstanceOf[Number].longValue()).toArray
      case _                => Array.empty[Long]

    val stats = out.stats
    Output(
      fBest = fBest,
      xBest = xBest,
      truthEvals = stats.truthEvals.asInstanceOf[Number].longValue(),
      partialSteps = stats.partialSteps.asInstanceOf[Number].longValue(),
      cheapRejects = stats.cheapRejects.asInstanceOf[Number].longValue(),
      invalidEvalRejects = stats.invalidEvalRejects.asInstanceOf[Number].longValue(),
    )
